### ISSUE TITLE
how to reset password

### ISSUE THREAD

**Issue by gmankab** [glaumar/v2raya-flatpak#5]
`flatpak run io.github.glaumar.v2raya_flatpak --reset_password` not works

**Comment by glaumar** [comment]
In order to ensure that the configuration files are not deleted during updates, the default configuration directory is not used. To reset your password, try:
```shell
sudo -i 

killall v2raya

flatpak run --command=sh io.github.glaumar.v2raya_flatpak

v2raya -c $XDG_CONFIG_HOME/v2raya --reset-password

exit

systemctl start v2raya-flatpak.service
```

**Comment by glaumar** [comment]
Now supports resetting password in the menu. 

![Screenshot_20240228_214841](https://github.com/glaumar/v2raya-flatpak/assets/35051470/906bd22b-77cc-476c-a843-f0ee92df72ed)

**Comment by gmankab** [comment]
thanks
